# Generated by Django 4.1.7 on 2023-03-20 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_advisor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Scheduling", "verbose_name_plural": "Scheduling"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.AddField(
            model_name="event",
            name="day",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Day of the event",
                verbose_name="Day of the event",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Textual Notes",
                null=True,
                verbose_name="Textual Notes",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(help_text="Final time", verbose_name="Final time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(
                help_text="Starting time", verbose_name="Starting time"
            ),
        ),
    ]
