# Generated by Django 4.1.7 on 2023-03-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "schedule_advisor",
            "0002_alter_event_options_remove_event_description_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
