# Generated by Django 4.1.4 on 2023-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_advisor", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(max_length=400)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(name="Class",),
    ]
