# Generated by Django 4.1.7 on 2023-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0006_department_remove_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='abbre',
        ),
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
