# Generated by Django 4.1.7 on 2023-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0008_rename_department_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='crse_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='text',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
