# Generated by Django 4.1.7 on 2023-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0009_rename_title_course_crse_id_rename_text_course_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(max_length=200),
        ),
    ]
