# Generated by Django 4.1.7 on 2023-04-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0008_student_advisor'),
        ('schedule_advisor', '0010_alter_course_units'),
    ]

    operations = [
    ]
