# Generated by Django 4.1.7 on 2023-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0011_merge_0008_student_advisor_0010_alter_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
