# Generated by Django 4.1.7 on 2023-04-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0013_alter_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='crse_id',
            new_name='course_nbr',
        ),
    ]
