# Generated by Django 4.1.4 on 2023-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_advisor", "0014_rename_crse_id_course_course_nbr"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
