# Generated by Django 4.1.7 on 2023-05-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0016_profile_remove_student_user_delete_advisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_nbr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='catalog_nbr',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='class_capacity',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='class_nbr',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='class_section',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_available',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_total',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='meetings_days',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='meetings_end_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='meetings_facility_descr',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='meetings_start_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='wait_cap',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='wait_tot',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='descr',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
