# Generated by Django 4.1.7 on 2023-05-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_advisor', '0017_remove_course_course_nbr_remove_course_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
